---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
  # terraform-docs don't work quite well when is run recursively using pre-commit hooks
  # https://github.com/terraform-docs/terraform-docs/issues/613
  # Workaround: Run the command below instead:
  # for directory in modules/*/ ; do terraform-docs markdown table --output-file README.md $directory; done
  #- repo: https://github.com/terraform-docs/terraform-docs
    #rev: "v0.16.0"
    #hooks:
      #- id: terraform-docs-go
        #args: ["-c", "tf-modules/terraform-docs.yaml", "."]